# Generated by Django 4.2.2 on 2023-06-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='encrypted_password',
            field=models.BinaryField(max_length=50, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='encryption_iv',
            field=models.BinaryField(max_length=32),
        ),
    ]
