# Generated by Django 4.2.2 on 2023-07-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_manager', '0002_alter_passwordentry_encrypted_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordentry',
            name='auth_tag',
            field=models.BinaryField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='passwordentry',
            name='encrypted_password',
            field=models.BinaryField(max_length=50, verbose_name='encrypted password'),
        ),
    ]
