# Generated by Django 4.2.2 on 2023-07-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_manager', '0003_passwordentry_auth_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordentry',
            options={'ordering': ['-is_in_bookmarks', 'website'], 'verbose_name': 'password entry', 'verbose_name_plural': 'password entries'},
        ),
    ]
