# Generated by Django 4.2.2 on 2023-07-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_manager', '0004_alter_passwordentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordentry',
            options={'ordering': ['website', '-is_in_bookmarks', 'title'], 'verbose_name': 'password entry', 'verbose_name_plural': 'password entries'},
        ),
    ]
